service: aws-ejemp-serv
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  profile: deploy-aws
  region: us-east-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
